name: Deploy React application

on:
    push: 
        branches: 
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Source
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t asishdevops/reactjs-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL=${{secrets.REACT_APP_SERVER_BASE_URL}} .
            - name: Publish to Docker Hub
              run: docker push asishdevops/reactjs-app:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Check Docker Version
              run: docker --version
            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Pull Image from Docker Hub
              run: docker pull asishdevops/reactjs-app:latest

            - name: Delete Old Container
              run: docker rm -rf reactjs-app-container

            - name: Run Docker container
              run: |
                docker run -d -p 5000:5000 --name reactjs-app-container asishdevops/reactjs-app:latest
